name: wp-bedrock-deployer
on:
  push:
    branches:
      - main
env:
  PHP_VERSION: 7.4
  PHP_TOOLS: wp
  WP_ENV: 'staging'
  REMOTE_PATH: 'wp.digitalandy.eu'

concurrency: ${{ env.WP_ENV }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Prepare the enviorment
        uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: ${{ env.PHP_TOOLS }}

      - id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            ~/.wp-cli/packages
            ~/.wp-cli/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: wp-cli config
        run: wp cli wp package install aaemnnosttv/wp-cli-login-command && wp package install aaemnnosttv/wp-cli-dotenv-command

      - name: vendor_wp
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> /home/runner/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -a --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ env.REMOTE_PATH }} --exclude-from='.distignore' --dry-run

      - name: Create the .env
        run: touch .env && echo ${{ secrets.SSH_USER }} > .env

      - name: Continue install on a Server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ${{ env.REMOTE_PATH }} && wp --info'