name: WP PHP Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PHP_VERSION: 7.4
  PHP_TOOLS: wp
  WP_ENV: 'staging'
  REMOTE_PATH: 'wp.digitalandy.eu'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.24.0
      with:
        php-version: ${{ env.PHP_VERSION }}
        tools: ${{ env.PHP_TOOLS }}

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: wp-cli config
      run: wp package install aaemnnosttv/wp-cli-dotenv-command

    - name: wp dotenv create .env
      run: wp dotenv init --file=.env --with-salts --template=.env.${{ env.WP_ENV }} && wp dotenv set ACF_PRO_KEY ${{ secrets.ACF_PRO_KEY }}

    - name: switch to sqlite
      run: wp config set USE_MYSQL false --raw

    - name: Install Composer's dependencies
      run: composer install --prefer-dist --no-progress --no-scripts --no-dev --no-interaction --no-ansi --optimize-autoloader

    - name: Install wp stuff
      run: wp login install --activate && wp language core install cs_CZ uk en_GB && wp language plugin install --all cs_CZ uk en_GB && wp language theme install --all cs_CZ uk en_GB
      
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.5.0
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    
    - name: Add SSH Key to known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> /home/runner/.ssh/known_hosts

    - name: Deploy with rsync
      run: rsync -av --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ env.REMOTE_PATH }} --exclude-from='.distignore' --backup-dir='~/rsync-backups'

    - name: Continue install on a Server
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ${{ env.REMOTE_PATH }} && ls -lsa'
